### ISSUE TITLE
immortalwrt 21.02 能否加上homeproxy？

### ISSUE THREAD

**Issue by drw2005** [fantastic-packages/packages#11]
大佬，arm_cortex-a7架构，immortalwrt 21.02 能加上homeproxy这个插件吗？
感谢！

**Comment by muink** [comment]
不能，23.05才能用

**Comment by drw2005** [comment]
> 不能，23.05才能用

23.05好像也没有arm_cortex-a7架构的，能否加一个。

**Comment by muink** [comment]
之前是有的, 后来因为部署超限删了一批
您可以参考下面文档, fork项目自行部署
https://github.com/fantastic-packages/packages/blob/master/ForkTheProject.md
