### ISSUE TITLE
Request to make new apk packages available

### ISSUE THREAD

**Issue by sppmasterspp** [fantastic-packages/packages#16]
With this commit https://git.openwrt.org/?p=openwrt/openwrt.git;a=commit;h=40b8fbaa9754c86480eefc3692c9116a51a64718
apk was set as default package manager for OpenWrt main snapshot builds.
We need new apk packages to replace the old ipk ones.

**Comment by sppmasterspp** [comment]
> apk support will be provided in the 24.10 branch. The feature is still under development, please be patient.

OK. Thank you.

**Comment by muink** [comment]
apk now provided in [SNAPSHOT](https://fantastic-packages.github.io/packages/releases/SNAPSHOT/).
CC @aliakin85 @sppmasterspp

**Comment by sppmasterspp** [comment]
> apk now provided in [SNAPSHOT](https://fantastic-packages.github.io/packages/releases/SNAPSHOT/).

Thanks!
Any short "How to" so we can add APK repository, needed keys, etc. to the OpenWrt devices.
Like [this one](https://docs.openwrt.melmac.net/#OnyourOpenWrtdevicewithapk) for example.

**Comment by muink** [comment]
You just need to install [fantastic-keyring](https://fantastic-packages.github.io/packages/releases/SNAPSHOT/packages/x86_64/packages/fantastic-keyring-20241123-r1.apk) and ~`fantastic-packages-feeds`~
But `fantastic-packages-feeds` currently does not support apk.
You need to manually add the following to `/etc/apk/repositories.d/customfeeds.list`
```
https://fantastic-packages.github.io/packages/releases/SNAPSHOT/packages/x86_64/luci/packages.adb
https://fantastic-packages.github.io/packages/releases/SNAPSHOT/packages/x86_64/packages/packages.adb
https://fantastic-packages.github.io/packages/releases/SNAPSHOT/packages/x86_64/special/packages.adb
```
`x86_64` needs to be replaced with the architecture of your device.

**Comment by aliakin85** [comment]
Thanks

Op vr 6 dec 2024 om 17:17 schreef Anya Lin ***@***.***>

**Comment by sppmasterspp** [comment]
> You just need to install [fantastic-keyring](https://fantastic-packages.github.io/packages/releases/SNAPSHOT/packages/x86_64/packages/fantastic-keyring-20241123-r1.apk) and ~`fantastic-packages-feeds`~
> But `fantastic-packages-feeds` currently does not support apk.
> You need to manually add the following to `/etc/apk/repositories.d/customfeeds.list`

I did this but unfortunately it gives an error - UNTRUSTED signature.
```
fetch https://fantastic-packages.github.io/packages/releases/SNAPSHOT/packages/aarch64_cortex-a53/luci/packages.adb
WARNING: updating and opening https://fantastic-packages.github.io/packages/releases/SNAPSHOT/packages/aarch64_cortex-a53/luci/packages.adb: UNTRUSTED signature
```
As a result packages are not found and cannot be added.
So without a .PEM key I guess it's not going to work.
One can still use `apk --allow-untrusted add` from terminal but that is not so convenient.

**Comment by muink** [comment]
So you need to install `fantastic-keyring` manually, which contains the necessary pem key.

**Comment by muink** [comment]
In addition if you are installing the key manually, `20241123170031.pub` will be what you need.
https://fantastic-packages.github.io/packages/releases/SNAPSHOT/

**Comment by sppmasterspp** [comment]
> So you need to install `fantastic-keyring` manually, which contains the necessary pem key.

I installed it manually and the feeds were there but they disappear after firmware update. Should I do this after every update?

**Comment by muink** [comment]
@sppmasterspp yes

**Comment by 1ucay** [comment]
Please add this to readme.

**Comment by 1ucay** [comment]
So you need 
apk --allow-untrusted add fantastic-keyring-XXX.apk

**Comment by muink** [comment]
@1ucay Added https://github.com/fantastic-packages/packages/tree/gh-pages#readme
