### ISSUE TITLE
OPKG does not notice that the package has been updated

### ISSUE THREAD

**Issue by remittor** [fantastic-packages/packages#3]
**Problem:**
I have installed package `luci-theme-argon_2.3.1_all.ipk`:
```
root@OpenWrt:~# opkg info luci-theme-argon
Package: luci-theme-argon
Version: 2.3.1
Depends: libc, curl, jsonfilter, luci-lua-runtime
Status: install user installed
Section: luci
Architecture: all
Size: 389176
Filename: luci-theme-argon_2.3.1_all.ipk
Description: Argon Theme
Installed-Time: 1691213874
```

OPKG src list:
```
root@OpenWrt:~# opkg update
Downloading https://fantastic-packages.github.io/packages/releases/23.05/packages/aarch64_cortex-a53/luci/Packages.gz
Updated list of available packages in /var/opkg-lists/fantastic_packages_luci
Downloading https://fantastic-packages.github.io/packages/releases/23.05/packages/aarch64_cortex-a53/luci/Packages.sig
Signature check passed.
Downloading https://fantastic-packages.github.io/packages/releases/23.05/packages/aarch64_cortex-a53/packages/Packages.gz
Updated list of available packages in /var/opkg-lists/fantastic_packages_packages
Downloading https://fantastic-packages.github.io/packages/releases/23.05/packages/aarch64_cortex-a53/packages/Packages.sig
Signature check passed.
...
```

Request info for a new version for packages:
```
root@OpenWrt:~# opkg list-installed | grep argon
luci-app-argon-config - 1.0
luci-theme-argon - 2.3.1

root@OpenWrt:~# opkg list-upgradable | grep argon

```

**Reason**:
The update system only pays attention to the package version.

**Solve**:
You need to add the date of the last git commit to the package version.

**Comment by muink** [comment]
Recommend:
`opkg install --force-reinstall luci-theme-argon`

To solve the problem, please go to the upstream and submit a PR.
https://github.com/jerrykuku/luci-theme-argon

**Comment by remittor** [comment]
> Recommend:
> `opkg install --force-reinstall luci-theme-argon`

How should the user understand that he needs to call this command?

> To solve the problem, please go to the upstream and submit a PR.

This problem is not limited to this package.

**Comment by remittor** [comment]
I now turned my attention to package `luci-app-homeproxy`.
This package has no version at Makefile: `luci-app-homeproxy_unknown_all.ipk`
