### ISSUE TITLE
error

### ISSUE THREAD

**Issue by GWan1234** [fantastic-packages/packages#9]
Collected errors:
 * pkg_hash_check_unresolved: cannot find dependency netdata-ssl for luci-app-netdata
 * pkg_hash_fetch_best_installation_candidate: Packages for luci-app-netdata found, but incompatible with the architectures configured
 * opkg_install_cmd: Cannot install package luci-app-netdata.
 * satisfy_dependencies_for: Cannot satisfy the following dependencies for luci-i18n-netdata-zh-cn:
 * 	netdata-ssl
 * opkg_install_cmd: Cannot install package luci-i18n-netdata-zh-cn.
 * pkg_hash_check_unresolved: cannot find dependency qbittorrent for luci-app-qbittorrent
 * pkg_hash_fetch_best_installation_candidate: Packages for luci-app-qbittorrent found, but incompatible with the architectures configured
 * opkg_install_cmd: Cannot install package luci-app-qbittorrent.
 * satisfy_dependencies_for: Cannot satisfy the following dependencies for luci-i18n-qbittorrent-zh-cn:
 * 	qbittorrent
 * opkg_install_cmd: Cannot install package luci-i18n-qbittorrent-zh-cn.
make[2]: *** [package/Makefile:71: package/install] Error 255
make[2]: Leaving directory '/home/u/Documents/openwrt-01170d51'
make[1]: *** [package/Makefile:124: /home/u/Documents/openwrt-01170d51/staging_dir/target-x86_64_musl/stamp/.package_install] Error 2
make[1]: Leaving directory '/home/u/Documents/openwrt-01170d51'

**Comment by muink** [comment]
> cannot find dependency **netdata-ssl** for luci-app-netdata
cannot find dependency **qbittorrent** for luci-app-qbittorrent

Please execute in repo:
```
git remote update -p
git submodule update --init --recursive
```
Please execute in openwrt topdir:
```
scripts/feeds update -a
scripts/feeds install -a
```
